//! Concrete instantiation of the workplace hierarchy theory.
//!
//! The full reference encoding lives in `theories/workplace.smt`.  This module
//! expresses the predicate-logic subset that the current IR supports: Horn
//! clauses and integrity constraints over binary relations.  Function-valued
//! axioms (e.g. `works_in` coherence) require term-level support not yet in
//! the macro and are omitted here.
//!
//! # Axiom catalogue
//!
//! | ID | Name | `implicit_by_default` | Source |
//! |----|------|-----------------------|--------|
//! | T1 | `manages_plus_base` | true | auto (transitive_closure!) |
//! | T2 | `manages_plus_step` | true | auto (transitive_closure!) |
//! | A1 | `chain_of_command_can_fire` | true | A1/A2 in reference |
//! | A2 | `chain_of_command_can_approve` | true | A3/A4 in reference |
//! | C1 | `fired_implies_authority` | false | C1 in reference |
//! | C2 | `approved_implies_authority` | false | C2 in reference |
//! | C3 | `fired_implies_chain` | true | abductive bridge for indirect facts |
//! | C4 | `approved_implies_chain` | true | abductive bridge for indirect facts |
//! | I1 | `no_self_fire` | true | I1 in reference |
//! | I2 | `no_self_approve` | true | I2 in reference |
//! | I3 | `no_self_manage` | true | S6/structural |
//! | I4 | `manages_antisymmetry` | true | S7 in reference |
//!
//! Plus completion axioms auto-generated by `finalize_completions` for each
//! `cwa: true` predicate with Horn rules: `completion_can_fire`,
//! `completion_can_approve_expense`, `completion_manages_plus`.
//!
//! The role predicates `is_ceo` and `is_head_of_department` are `cwa: true`
//! but have no Horn rules, so the SMT backend handles their negation
//! unconditionally at instance load (no ablatable completion). Ground facts
//! `is_ceo(ceo)` and `is_head_of_department(head_i, dept_i)` are emitted by
//! the generator.
//!
//! # Usage
//!
//! ```rust,ignore
//! let theory = workplace::theory();
//! let instance = theory.instantiate(domain);
//! ```

use std::cell::RefCell;
use std::collections::VecDeque;
use std::sync::OnceLock;

use rand::{Rng, RngExt, seq::IndexedRandom};
use rand_distr::{Distribution, Poisson};

use crate::rendering::{NameInitializer, NameMap};
use crate::theories::{
    Atom, ConstId, Formula, GroundModel, Instance, ModelGenerator, QueryGenerator, SymbolId, Term,
    Theory,
};

mod departments;
mod names;

/// Return a reference to the (lazily initialised) workplace `Theory`.
///
/// The `Theory` is built once and stored in a process-wide static.  Subsequent
/// calls return a reference to the same value with no allocation.
pub fn theory() -> &'static Theory {
    static THEORY: OnceLock<Theory> = OnceLock::new();
    THEORY.get_or_init(build)
}

/// Sampler for workplace puzzle queries.
///
/// Picks an authority predicate (`can_fire` or `can_approve_expense`) and an
/// ordered pair of employees. Two flavors, sampled with equal probability:
///
/// - **Yes-query**: a derived authority atom from the LFP. Ground-truth
///   answer is "yes" (entailed); ablating a load-bearing Horn axiom can
///   render it underdetermined.
/// - **No-query**: a self-pair `pred(p, p)`, forbidden by the
///   `no_self_fire` / `no_self_approve` integrity axioms. Ground-truth
///   answer is "no" (refuted); ablating the relevant integrity axiom
///   renders it underdetermined.
///
/// Both flavors restrict to derived predicates so the puzzle exercises the
/// implicit theory.
pub struct WorkplaceQueryGenerator<R> {
    rng: R,
}

impl<R> WorkplaceQueryGenerator<R> {
    pub fn new(rng: R) -> Self {
        Self { rng }
    }
}

impl<R> QueryGenerator<'static> for WorkplaceQueryGenerator<R>
where
    R: Rng,
{
    fn generate(&mut self, model: &GroundModel<'static>) -> Formula {
        let t = model.theory();
        let can_fire_sym = t.find_symbol("can_fire");
        let can_approve_sym = t.find_symbol("can_approve_expense");

        let yes_query = self.rng.random_bool(0.5);
        let (sym, p, q) = if yes_query {
            let lfp = model.entailed_predicates();
            let derived: Vec<(SymbolId, ConstId, ConstId)> = lfp
                .iter()
                .filter_map(|(s, args)| {
                    if (*s == can_fire_sym || *s == can_approve_sym)
                        && args.len() == 2
                        && args[0] != args[1]
                    {
                        Some((*s, args[0], args[1]))
                    } else {
                        None
                    }
                })
                .collect();
            assert!(
                !derived.is_empty(),
                "no derived authority atoms — cannot generate a yes-query"
            );
            *derived.choose(&mut self.rng).unwrap()
        } else {
            // Pick any pair (p, q) such that the predicate does NOT hold under
            // the full theory. Includes self-pairs (forbidden by no_self_*)
            // and unrelated pairs (forbidden by the predicate's completion).
            let employee_sort = t.find_sort("employee");
            let employees: &[ConstId] = model
                .domain()
                .get(&employee_sort)
                .map(Vec::as_slice)
                .unwrap_or(&[]);
            let lfp = model.entailed_predicates();
            let mut candidates: Vec<(SymbolId, ConstId, ConstId)> = Vec::new();
            for &sym in &[can_fire_sym, can_approve_sym] {
                for &p in employees {
                    for &q in employees {
                        if !lfp.contains(&(sym, vec![p, q])) {
                            candidates.push((sym, p, q));
                        }
                    }
                }
            }
            assert!(
                !candidates.is_empty(),
                "no non-derived authority atoms — cannot generate a no-query"
            );
            *candidates.choose(&mut self.rng).unwrap()
        };

        Formula::Atom(Atom::Predicate {
            symbol: sym,
            args: vec![Term::DomainConst(p), Term::DomainConst(q)],
        })
    }
}

/// Construct the workplace `Theory`.  Called at most once by [`theory`].
fn build() -> Theory {
    let mut t = theory! {
        // Natural language preamble
        preamble! (
            "The following is a logic puzzle about workplace relations within a \
            company. The company has some number of departments and is staffed \
            by employees, including a CEO, department heads, and other staff. \
            The facts below describe who manages whom, who works in which \
            department, and which firing or expense-approval actions have \
            occurred. The rules describe how authority is derived from these \
            facts. Use the facts and rules to answer the question at the end."
        );

        // ------------------------------------------------------------------
        // Sorts
        // ------------------------------------------------------------------
        sorts!(employee, department);

        // ------------------------------------------------------------------
        // Structural functions
        // Every employee works in at most one department.
        // (Axioms involving function terms are not yet expressed here; the
        //  function is declared for use by Instance-level SMT translation.)
        // ------------------------------------------------------------------
        functions!(
            works_in {
                (employee) -> department,
                nl: "{0} works in {ret}"
            },
        );

        // ------------------------------------------------------------------
        // Relations
        // ------------------------------------------------------------------
        predicates!(
            manages {
                (employee, employee),
                nl: "{0} manages {1}",
                cwa: true
            },
            can_fire {
                (employee, employee),
                nl: "{0} can fire {1}",
                cwa: true
            },
            can_approve_expense {
                (employee, employee),
                nl: "{0} can approve an expense for {1}",
                cwa: true
            },
            fired {
                (employee, employee),
                nl: "{0} fired {1}",
                cwa: true
            },
            approved_expense {
                (employee, employee),
                nl: "{0} approved an expense for {1}",
                cwa: true
            },
            is_ceo {
                (employee),
                nl: "{0} is the CEO",
                cwa: true
            },
            is_head_of_department {
                (employee, department),
                nl: "{0} is the head of {1}",
                cwa: true
            },
        );

        // ------------------------------------------------------------------
        // Transitive closure of `manages` — the chain-of-command relation.
        // Auto-emits base and step Horn rules; with cwa: true (set by the
        // macro), `finalize_completions` produces the inductive definition,
        // making the closure ablatable.
        // ------------------------------------------------------------------
        transitive_closure!(
            manages -> manages_plus {
                nl: "{0} is somewhere above {1} in the management chain"
            },
        );

        // ------------------------------------------------------------------
        // A. Anywhere in the chain-of-command grants firing authority.
        // ------------------------------------------------------------------
        horn! {
            name:     "chain_of_command_can_fire",
            implicit: true,
            nl: "If someone is above another person in the chain of command, \
                 they can fire that person.",
            forall (p: employee, q: employee) {
                body: manages_plus(p, q);
                head: can_fire(p, q);
            }
        };

        // ------------------------------------------------------------------
        // B. Anywhere in the chain-of-command grants expense-approval authority.
        // ------------------------------------------------------------------
        horn! {
            name:     "chain_of_command_can_approve",
            implicit: true,
            nl: "If someone is above another person in the chain of command, \
                 they can approve their expenses.",
            forall (p: employee, q: employee) {
                body: manages_plus(p, q);
                head: can_approve_expense(p, q);
            }
        };

        // ------------------------------------------------------------------
        // C1. Act coherence: firing implies authority.
        // ------------------------------------------------------------------
        horn! {
            name:     "fired_implies_authority",
            implicit: false,
            nl:       "If p fired q, then p had authority to do so.",
            forall (p: employee, q: employee) {
                body: fired(p, q);
                head: can_fire(p, q);
            }
        };

        // ------------------------------------------------------------------
        // C2. Act coherence: expense approval implies authority.
        // ------------------------------------------------------------------
        horn! {
            name:     "approved_implies_authority",
            implicit: false,
            nl:       "If p approved q's expense, then p had authority to do so.",
            forall (p: employee, q: employee) {
                body: approved_expense(p, q);
                head: can_approve_expense(p, q);
            }
        };

        // ------------------------------------------------------------------
        // C3. Abductive bridge: if p fired q, then p is above q in the
        // chain of command. The puzzle generator can replace a direct
        // `manages` fact with `fired(p,q)`; this axiom is what re-derives
        // the missing chain edge. Implicit / ablatable — the oracle is
        // expected to supply it.
        // ------------------------------------------------------------------
        horn! {
            name:     "fired_implies_chain",
            implicit: true,
            nl: "If p fired q, then p is somewhere above q in the management chain.",
            forall (p: employee, q: employee) {
                body: fired(p, q);
                head: manages_plus(p, q);
            }
        };

        // ------------------------------------------------------------------
        // C4. Abductive bridge: expense approval implies chain-of-command.
        // ------------------------------------------------------------------
        horn! {
            name:     "approved_implies_chain",
            implicit: true,
            nl: "If p approved q's expense, then p is somewhere above q in the management chain.",
            forall (p: employee, q: employee) {
                body: approved_expense(p, q);
                head: manages_plus(p, q);
            }
        };

        // ------------------------------------------------------------------
        // I1. No one can fire themselves.
        // ------------------------------------------------------------------
        integrity! {
            name:     "no_self_fire",
            implicit: true,
            nl:       "No one can fire themselves.",
            forall (p: employee) {
                body: can_fire(p, p);
            }
        };

        // ------------------------------------------------------------------
        // I2. No one can approve their own expenses.
        //     Classic integrity rule; a key trap for the oracle.
        // ------------------------------------------------------------------
        integrity! {
            name:     "no_self_approve",
            implicit: true,
            nl:       "No one can approve their own expenses.",
            forall (p: employee) {
                body: can_approve_expense(p, p);
            }
        };

        // ------------------------------------------------------------------
        // I3. No one manages themselves.
        // ------------------------------------------------------------------
        integrity! {
            name:     "no_self_manage",
            implicit: true,
            nl:       "No one manages themselves.",
            forall (p: employee) {
                body: manages(p, p);
            }
        };

        // ------------------------------------------------------------------
        // I4. There are no cycles in the manamgement chain
        // ------------------------------------------------------------------
        integrity! {
            name:     "manages_antisymmetry",
            implicit: true,
            nl:       "There are no cycles in the management chain.",
            forall (p: employee, q: employee) {
                body: manages_plus(p, q), manages_plus(q, p);
            }
        };
    };
    t.finalize_completions();
    t
}

/// Generator for ground truth workplace hierarchies.
pub struct WorkplaceGenerator<R> {
    rng: R,
    offspring_distr: Poisson<f64>,
    max_depth: usize,
    n_departments: usize,
    /// Probability that a given `manages(p,q)` edge is emitted indirectly as
    /// `fired(p,q)` or `approved_expense(p,q)` instead of as a direct
    /// `manages` fact. The abductive-bridge axioms (`fired_implies_chain`,
    /// `approved_implies_chain`) restore the chain-of-command edge when the
    /// oracle is consulted; ablating those axioms turns these edges into
    /// dead ends for the puzzle solver.
    indirect_evidence_rate: f64,
}

impl<R> WorkplaceGenerator<R> {
    /// Create a new [`WorkplaceGenerator`], failing if the span of control is
    /// invalid for a [`Poisson`] distribution.
    pub fn try_new(
        rng: R,
        span_of_control: f64,
        max_depth: usize,
        n_departments: usize,
        indirect_evidence_rate: f64,
    ) -> Result<Self, rand_distr::PoissonError> {
        Poisson::new(span_of_control).map(|offspring_distr| Self {
            rng,
            offspring_distr,
            max_depth,
            n_departments,
            indirect_evidence_rate,
        })
    }
}

impl<R> ModelGenerator<'static> for WorkplaceGenerator<R>
where
    R: Rng,
{
    fn generate(&mut self) -> GroundModel<'static> {
        let t = theory();
        let employee_sort = t.find_sort("employee");
        let department_sort = t.find_sort("department");
        let manages_sym = t.find_symbol("manages");
        let fired_sym = t.find_symbol("fired");
        let approved_sym = t.find_symbol("approved_expense");
        let works_in_sym = t.find_symbol("works_in");
        let is_ceo_sym = t.find_symbol("is_ceo");
        let is_head_sym = t.find_symbol("is_head_of_department");

        let mut model = GroundModel::new(t);

        let departments: Vec<ConstId> = (0..self.n_departments)
            .map(|i| model.add_constant(format!("dept_{i}"), department_sort))
            .collect();

        let ceo = model.add_constant("ceo", employee_sort);
        model.add_predicate_fact(is_ceo_sym, vec![ceo]);

        // Emit an edge p→q either as `manages(p,q)` (direct) or, with
        // probability `indirect_evidence_rate`, as one of `fired(p,q)` /
        // `approved_expense(p,q)`. The abductive-bridge axioms recover the
        // chain-of-command edge from the indirect form when active.
        let mut emit_edge =
            |model: &mut GroundModel<'static>, rng: &mut R, parent: ConstId, child: ConstId| {
                if rng.random_bool(self.indirect_evidence_rate.clamp(0.0, 1.0)) {
                    let sym = if rng.random_bool(0.5) {
                        fired_sym
                    } else {
                        approved_sym
                    };
                    model.add_predicate_fact(sym, vec![parent, child]);
                } else {
                    model.add_predicate_fact(manages_sym, vec![parent, child]);
                }
            };

        // BFS frontier: (manager, depth, department).
        let mut frontier: VecDeque<(ConstId, usize, ConstId)> = VecDeque::new();
        for (i, &dept) in departments.iter().enumerate() {
            let head = model.add_constant(format!("head_{i}"), employee_sort);
            emit_edge(&mut model, &mut self.rng, ceo, head);
            model.add_function_fact(works_in_sym, vec![head], dept);
            model.add_predicate_fact(is_head_sym, vec![head, dept]);
            frontier.push_back((head, 1, dept));
        }

        let mut next_id: usize = 0;
        while let Some((parent, depth, dept)) = frontier.pop_front() {
            if depth >= self.max_depth {
                continue;
            }
            let n_children = self.offspring_distr.sample(&mut self.rng) as usize;
            for _ in 0..n_children {
                let child = model.add_constant(format!("emp_{next_id}"), employee_sort);
                next_id += 1;
                emit_edge(&mut model, &mut self.rng, parent, child);
                model.add_function_fact(works_in_sym, vec![child], dept);
                frontier.push_back((child, depth + 1, dept));
            }
        }

        model
    }
}

/// Assigns pretty natural-language names to a workplace `Instance`'s domain
/// constants. Stable names like `dept_0`, `head_2`, `emp_7` are mapped to
/// real-sounding department names (Engineering, Finance, ...) and people
/// names (Alice, Brianna, ...). The CEO and department heads receive ordinary
/// personal names too — their role is exposed only via the `is_ceo` /
/// `is_head_of_department` facts, not baked into how they're referred to.
pub struct WorkplaceNameInitializer<R> {
    rng: RefCell<R>,
}

impl<R> WorkplaceNameInitializer<R> {
    pub fn new(rng: R) -> Self {
        Self {
            rng: RefCell::new(rng),
        }
    }
}

impl<R> NameInitializer for WorkplaceNameInitializer<R>
where
    R: Rng,
{
    fn init_map(&self, instance: &Instance<'_>, map: &mut NameMap) {
        let theory = instance.theory();
        let employee_sort = theory.find_sort("employee");
        let department_sort = theory.find_sort("department");

        let mut depts: Vec<(usize, ConstId)> = Vec::new();
        let mut heads: Vec<(usize, ConstId)> = Vec::new();
        let mut emps: Vec<(usize, ConstId)> = Vec::new();
        let mut ceo: Option<ConstId> = None;

        for (id, decl) in instance.constants() {
            let stable = decl.name();
            if decl.sort() == department_sort {
                if let Some(i) = stable.strip_prefix("dept_").and_then(|s| s.parse().ok()) {
                    depts.push((i, id));
                }
            } else if decl.sort() == employee_sort {
                if stable == "ceo" {
                    ceo = Some(id);
                } else if let Some(i) = stable.strip_prefix("head_").and_then(|s| s.parse().ok()) {
                    heads.push((i, id));
                } else if let Some(i) = stable.strip_prefix("emp_").and_then(|s| s.parse().ok()) {
                    emps.push((i, id));
                }
            }
        }

        depts.sort_by_key(|(i, _)| *i);
        heads.sort_by_key(|(i, _)| *i);
        emps.sort_by_key(|(i, _)| *i);

        let mut rng = self.rng.borrow_mut();

        let dept_names = departments::random_balanced_names(&mut *rng, depts.len());
        for (&(_, id), name) in depts.iter().zip(dept_names.iter()) {
            map.insert(id, name.to_string());
        }

        // Draw personal names for every employee — CEO, heads, and
        // rank-and-file alike — from a single pool. We shouldn't leak the role
        // through the rendered name; whether someone is the CEO or a department
        // head is something the solver must infer from `is_ceo` /
        // `is_head_of_department` facts (when rendered) or from the management
        // structure.
        let total_emps = ceo.is_some() as usize + heads.len() + emps.len();
        let emp_names = names::random_balanced_names(&mut *rng, total_emps);
        let mut name_iter = emp_names.iter();

        if let Some(id) = ceo {
            map.insert(
                id,
                name_iter
                    .next()
                    .expect("name pool sized for ceo+heads+emps")
                    .to_string(),
            );
        }
        for &(_, id) in &heads {
            map.insert(
                id,
                name_iter
                    .next()
                    .expect("name pool sized for ceo+heads+emps")
                    .to_string(),
            );
        }
        for &(_, id) in &emps {
            map.insert(
                id,
                name_iter
                    .next()
                    .expect("name pool sized for ceo+heads+emps")
                    .to_string(),
            );
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn workplace_theory_structure() {
        let t = theory();

        // 2 sorts: employee, department
        assert_eq!(t.sorts().count(), 2);

        // 1 function + 8 predicates (manages, can_fire, can_approve_expense,
        // fired, approved_expense, manages_plus, is_ceo,
        // is_head_of_department) = 9 symbols.
        assert_eq!(t.symbols().count(), 9);

        // 12 declared axioms (2 manages_plus base/step + 2 chain-of-command
        // + 2 act-coherence + 2 abductive bridges + 4 integrity) plus 3
        // auto-generated completions (can_fire, can_approve_expense,
        // manages_plus). `is_ceo` and `is_head_of_department` are CWA
        // predicates with no Horn rules, so they receive no theory-level
        // completion — the SMT backend handles their negations at load.
        assert_eq!(t.axioms().count(), 15);

        // Implicit axioms: manages_plus base+step, chain-of-command x2,
        // 2 abductive bridges, no_self_* x3, manages_antisymmetry, 3
        // completions = 13.
        let implicit: Vec<_> = t
            .axioms()
            .filter(|(_, a)| a.implicit_by_default())
            .collect();
        assert_eq!(implicit.len(), 13);

        // Spot-check names
        let names: std::collections::HashSet<&str> = t.axioms().map(|(_, a)| a.name()).collect();
        assert!(names.contains("chain_of_command_can_fire"));
        assert!(names.contains("no_self_approve"));
        assert!(names.contains("manages_antisymmetry"));
        assert!(names.contains("manages_plus_base"));
        assert!(names.contains("manages_plus_step"));
        assert!(names.contains("completion_can_fire"));
        assert!(names.contains("completion_can_approve_expense"));
        assert!(names.contains("completion_manages_plus"));
    }

    #[test]
    fn workplace_theory_is_singleton() {
        // Both calls must return the same address.
        let a = theory() as *const Theory;
        let b = theory() as *const Theory;
        assert_eq!(a, b);
    }
}
